services:
  rapidex-api:
    image: wiremock/wiremock:3x
    command: --verbose
    ports:
      - "8081:8080"
    volumes:
      - ./.docker/wiremock:/home/wiremock/mappings

  algashop-postgres:
    image: postgres:18-alpine
    restart: always
    shm_size: 128mb
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - algashop-postgres:/var/lib/postgresql
      - .docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  algashop-postgres: