include:
  - docker-compose.tools.yaml

services:
  algashop-ordering:
    image: algashop/ordering:dev
    restart: no
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      algashop-postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M

  algashop-billing:
    image: algashop/billing:dev
    restart: no
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8080"
    depends_on:
      algashop-postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M